// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEozgiDXnbG-DFbLXJj3TUV6NpAozyzBI',
    appId: '1:982828684144:web:f5200b9fc3e5c6d53df5b5',
    messagingSenderId: '982828684144',
    projectId: 'infoplus-96862',
    authDomain: 'infoplus-96862.firebaseapp.com',
    storageBucket: 'infoplus-96862.appspot.com',
    measurementId: 'G-M9J7ZDH6DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxDhyWmUH6_F1_tJj3QK9sIfp8z21L7bY',
    appId: '1:982828684144:android:a403acb063d2d9b23df5b5',
    messagingSenderId: '982828684144',
    projectId: 'infoplus-96862',
    storageBucket: 'infoplus-96862.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3jGJJmKu_8NCpF5-PqVgv7wib9v3aiQ4',
    appId: '1:982828684144:ios:c76b00b3021db4ef3df5b5',
    messagingSenderId: '982828684144',
    projectId: 'infoplus-96862',
    storageBucket: 'infoplus-96862.appspot.com',
    iosBundleId: 'com.example.projetoInfoplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3jGJJmKu_8NCpF5-PqVgv7wib9v3aiQ4',
    appId: '1:982828684144:ios:c76b00b3021db4ef3df5b5',
    messagingSenderId: '982828684144',
    projectId: 'infoplus-96862',
    storageBucket: 'infoplus-96862.appspot.com',
    iosBundleId: 'com.example.projetoInfoplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEozgiDXnbG-DFbLXJj3TUV6NpAozyzBI',
    appId: '1:982828684144:web:9b4779005110fb333df5b5',
    messagingSenderId: '982828684144',
    projectId: 'infoplus-96862',
    authDomain: 'infoplus-96862.firebaseapp.com',
    storageBucket: 'infoplus-96862.appspot.com',
    measurementId: 'G-DG8L6WN9EG',
  );

}